### ISSUE TITLE
Can't get the res current folder to work 

### ISSUE THREAD

**Issue by gmarziou** [mwaylabs/generator-m-ionic#274] opened 2015-10-21 18:03 UTC
Hello,

I'm using 1.3.4 on Windows 7 with NodeJS 0.12.x

I forked the demo as https://github.com/gmarziou/generator-m-ionic-demo
and I tried to apply the [icon and splash screen guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/icons_splash_screens.md#using-the-rescurrent-folder) which explains how to use different icon sets using the res current folder.

I added these lines to my config.xml

``` xml
<!-- both icons are static in default folder -->
<platform name="android">
  <icon src="res/android/default/icon.png" />
</platform>
<platform name="ios">
  <icon src="res/ios/default/icon.png" />
</platform>
```

When I run `gulp --cordova "run android"`, it seems it does not copy the default folder to current.
Same error happens if I run `gulp --cordova "run android" --res=set1`

```
[19:54:27] Using gulpfile C:\projets\generator-m-ionic-demo\gulpfile.js
[19:54:27] Starting 'default'...
[19:54:27] Starting 'eslint-throw'...
[19:54:27] Starting 'jsonlint-throw'...
[19:54:28] Starting 'clean'...
[19:54:28] Starting 'wiredep'...
[19:54:28] Starting 'environment'...
[19:54:28] Starting 'clean-res'...
[19:54:28] Finished 'default' after 1.21 s
[19:54:28] Finished 'clean-res' after 18 ms
[19:54:28] Starting 'resources'...
[19:54:28] gulp-inject 1 files into blank\constants\blank-config-const.js.
[19:54:28] gulp-inject 1 files into main\constants\config-const.js.
[19:54:28] Finished 'wiredep' after 835 ms
[19:54:28] Finished 'jsonlint-throw' after 1.02 s
[19:54:28] gulp-inject 1 files into side\constants\side-config-const.js.
[19:54:28] Finished 'resources' after 748 ms
[19:54:29] Finished 'environment' after 1.01 s
[19:54:29] Starting 'build-vars'...
[19:54:29] gulp-inject 1 files into blank\constants\blank-config-const.js.
[19:54:29] gulp-inject 1 files into main\constants\config-const.js.
[19:54:29] gulp-inject 1 files into side\constants\side-config-const.js.
[19:54:29] Finished 'build-vars' after 268 ms
[19:54:29] Finished 'clean' after 1.39 s
[19:54:29] Starting 'styles'...
[19:54:30] Starting 'bower-fonts'...
[19:54:30] Starting 'build-templates'...
[19:54:30] Finished 'eslint-throw' after 3.81 s
[19:54:30] Starting 'linting-throw'...
[19:54:30] Finished 'linting-throw' after 13 ╬╝s
[19:54:30] Finished 'bower-fonts' after 539 ms
[19:54:30] Starting 'build-assets'...
[19:54:31] Finished 'styles' after 2.24 s
[19:54:31] Starting 'inject-all'...
[19:54:31] gulp-imagemin: Minified 0 images
[19:54:31] Finished 'build-assets' after 1.01 s
[19:54:31] Finished 'build-templates' after 1.42 s
[19:54:31] gulp-inject 12 files into index.html.
[19:54:31] gulp-inject 3 files into index.html.
[19:54:31] Finished 'inject-all' after 299 ms
[19:54:31] Starting 'build-app'...
[19:54:32] Finished 'build-app' after 967 ms
[19:54:32] Starting 'build'...
[19:54:33] index.html 1.25 kB
[19:54:33] fonts\ionicons.eot 120.72 kB
[19:54:33] fonts\ionicons.svg 333.83 kB
[19:54:33] fonts\ionicons.ttf 188.51 kB
[19:54:33] fonts\ionicons.woff 67.9 kB
[19:54:33] scripts\app.js 7.16 kB
[19:54:33] scripts\vendor.js 2.6 MB
[19:54:33] styles\vendor.css 223.72 kB
[19:54:33] main\styles\app.css 117 B
[19:54:33] side\templates\debug.html 1.78 kB
[19:54:33] side\templates\list-detail.html 360 B
[19:54:33] side\templates\list.html 483 B
[19:54:33] side\templates\menu.html 1.23 kB
[19:54:33] main\templates\debug.html 1.78 kB
[19:54:33] main\templates\list-detail.html 360 B
[19:54:33] main\templates\list.html 483 B
[19:54:33] main\templates\tabs.html 457 B
[19:54:33] main\assets\images\yo@2x.png 2.2 kB
[19:54:33] side\assets\images\yo@2x.png 2.2 kB
[19:54:33] all files 3.56 MB
[19:54:33] Finished 'build' after 197 ms
[19:54:33] Starting 'cordova-with-build'...
cp: no such file or directory: C:\projets\generator-m-ionic-demo\res\android\current\icon.png

Running command: "C:\Program Files (x86)\nodejs\node.exe" C:\projets\generator-m-ionic-demo\hooks\after_prepare\update_platform_config.js C:\projets\generator-m-ionic-demo

....

:processDebugResourcesC:\projets\generator-m-ionic-demo\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:24: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/icon').
```

**Comment by gmarziou** [comment] 2015-10-21 21:35
I ran same command on same project on Ubuntu and it worked, so I guess this could be a Windows specific issue

**Comment by gruppjo** [comment] 2015-10-27 09:21
Hi @gmarziou, thanks for reporting. Currently I don't have the opportunity to test this on a windows machine. I'll leave this open, maybe somebody else knows what to do.

**Comment by demege** [comment] 2015-11-02 14:25
Hi,

I read the doc about res folder:
https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/icons_splash_screens.md

But it didn't mention where is the location of the res folder after the build finish.
I executed:
$ gulp build

And the www folder don't have a /res folder inside, result:
/www
-- /main
-- /scripts
-- index.html

We are using phonegap build, so we are planning to include the "res" folder inside the www/.
There is any gulp task for that ?, or right now is handled with a cordova hook task ?

Regards

**Comment by gmarziou** [comment] 2015-11-03 09:26
As far as I know, it's not supposed to be copied under www, it is copied under C:\projets\ecobil\grand_public\platforms\android at build time

**Comment by gruppjo** [comment] 2017-01-27 16:09
@gmarziou, is this still an issue?

**Comment by gruppjo** [comment] 2017-02-01 14:32
closing, since the issue is outdated. Please feel free to comment, when you feel otherwise.

**Closed by gruppjo** 2017-02-01 14:32 UTC
Labels: bug, os: windows, support
