### ISSUE TITLE
config-const.js emptied on new file with gulp watch

### ISSUE THREAD

**Issue by ruddell** [mwaylabs/generator-m-ionic#363] opened 2016-05-01 18:26 UTC
Hey, I'm loving the generator, thank you for all of the work.  
##### **Overview of the issue**
When running `gulp watch`, if a new file is added to the project (copied or generated), the config-const.js file is erased (all lines of the file are removed).  This will then cause running the project and building the project to fail as there is no Config constant to inject.

The gulp output from the Reproduce the Error section below can be seen http://pastebin.com/raw/Dn6f8Ktw
##### **Version(s)** 
1.8
##### **Configuration file** 
```
{
  "generator-m-ionic": {
    "answers": {
      "appName": "test",
      "appId": "com.jruddell.test",
      "ionicCss": false,
      "bowerPackages": [
        "localforage#~1.4.0"
      ],
      "platforms": [],
      "plugins": [
        "cordova-plugin-device"
      ],
      "appModule": "test",
      "ecosystems": []
    }
  }
}
```

##### **Reproduce the error** 
```
mkdir test && cd test
yo m-ionic
gulp watch
```
In new terminal tab
```
yo m-ionic:controller test
```
Also happens if you copy a file into the project instead of generating a new one.

##### **Fix**
I haven't looked into how to fix it, not the best with gulp.

**Comment by ruddell** [comment] 2016-05-01 18:34
Related to #227 but happens with only `gulp watch`

**Comment by gruppjo** [comment] 2016-05-02 13:44
Hi @ruddell!
I couldn't reproduce your issue on my machine with our [demo repository](https://github.com/mwaylabs/generator-m-ionic-demo). Can you provide the following details?
```sh
# post the result of the following commands
node -v # node version
npm -v # npm version
npm list -g generator-m-ionic # generator version
```

- Which OS and version are you on?
- Please provide a Demo repository so I can check if something's wrong with your repo or something else

**Comment by ruddell** [comment] 2016-05-02 15:57
I can confirm that this issue does not occur on the demo project, but if you generate a project with the .yo-rc.json from my initial post, the issue is present.  I also experienced it with iOS as a platform

Repo with commits at each step (.yo-rc.json, generation, initial gulp watch, and changes after generating/adding a file) https://github.com/ruddell/m-ionic-test

| Program  | Version |
| ------------- | ------------- |
| Node  | v5.5.0  |
| NPM  | v3.7.3  |
| OS  | Mac  |
| OS Version  | El Capitan, 10.11.4  |

**Comment by gruppjo** [comment] 2016-05-02 18:32
Thank you for your very fine reporting and the nice demo repo! :)

Unfortunately I still cannot reproduce the issue. Here's what I did:
```sh
git clone git@github.com:ruddell/m-ionic-test.git
cd m-ionic-test
npm i && bower i
gulp watch
```
And then:
```sh
$ yo m-ionic:controller acontroller
You called the m-ionic:constant subgenerator.
You called the m-ionic:controller subgenerator.
   create app/main/controllers/acontroller-ctrl.js
   create test/karma/main/acontroller-ctrl.spec.js
$ gs
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	app/main/controllers/acontroller-ctrl.js
	test/karma/main/acontroller-ctrl.spec.js

no changes added to commit (use "git add" and/or "git commit -a")
```

I'd recommend deleting the `node_modules` folder and `npm i` again, but you probably tried that already, additionally this seems to occur independent from your project.

I'm out of ideas for now.

**Comment by ruddell** [comment] 2016-05-02 19:45
I'm sorry, I pushed the blank config file to show the flow of actions.  I reversed the commit and tested the repo again (using your process from the last post) and I get the following:
```
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/index.html
	modified:   app/main/constants/config-const.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	app/main/controllers/acontroller-ctrl.js
	test/karma/main/acontroller-ctrl.spec.js

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by gruppjo** [comment] 2016-05-03 08:00
Wops. Of course it didn't work then ;)

I tried again, 5 times and still I cannot reproduce.

However I noticed that sometimes the SCSS/CSS doesn't render after a new file is created. Do you get that as well?

**Comment by ruddell** [comment] 2016-05-03 19:47
I tested on a new ubuntu-upstart docker image and I could not reproduce the issue so it has to be something with my setup.  Sorry for taking up your time, but at least we found a different issue.

It looks like the css file is deleted and not recreated, leaving the project without styling.  Restarting `gulp watch` fixes it but I'm not sure if that's a solution.

**Comment by objectiveP** [comment] 2016-05-04 09:56
Hey, i just wanted to let you know that I have same issue, so maybe there is something more to it. Same with the css file.

**Comment by SadiSofiane** [comment] 2016-05-04 13:33
Same problem for me... 
In order to make it work I have to insert back the default config-const.js content before running a gulp watch

```
'use strict';
angular.module('main')
.constant('Config', {
  // gulp environment: injects environment vars
  ENV: {
    /*inject-env*/
    /*endinject*/
  },

  // gulp build-vars: injects build vars
  BUILD: {
    /*inject-build*/
    /*endinject*/
  }

});
```

**Comment by objectiveP** [comment] 2016-05-04 15:17
Are you guys using Webstorm (or whatever is based on IntelliJ) for editing? This could be the reason for the problem. My hypothesis is that is somehow an I/O issue between gulp and web storm indexing the file. I excluded the constants directory from the project scope, which fixed the problem for me. 

If that is the case, it is not problem of the generator and issue can be closed.

**Comment by SadiSofiane** [comment] 2016-05-04 16:50
I am using vim.

**Comment by gruppjo** [comment] 2016-05-06 14:02
Everybody willing to help or experiencing this issue, please provide the following formatted as below. That way I might find a way to reproduce this (which I currently cannot) and try to fix this.

- Do you experience this issue?
- *important*: does the problem occur without running any other gulp task?
- Which OS and version are you on?

```sh
# post the result of the following commands
node -v # node version
npm -v # npm version
npm list -g generator-m-ionic # generator version
gulp -v
```

For me this would be:
| Info  | Answer |
| ------------- | ------------- |
| Occurs?  | No  |
| Without other gulp tasks?  | No  |
| OS & Version  | Mac, El Capitan, 10.11.4  |
| Node  | v5.11.0  |
| NPM  | v3.8.6  |
| Generator  | v1.8.0  |
| Gulp  | v3.9.0  |

**Comment by ruddell** [comment] 2016-05-06 18:07
@gruppjo I believe this issue occurs when injecting into the same file more than once at the same time.  See the last comment https://github.com/klei/gulp-inject/issues/123

From the original post's gulp output log (seen when I reproduce the issue), two injections at the same time:
```
[12:15:15] gulp-inject 1 files into main/constants/config-const.js.
[12:15:15] Finished 'styles' after 1.4 s
[12:15:15] gulp-inject 1 files into main/constants/config-const.js.
```

In injecting.js, the `environment` task is called from two different places, both injecting into config-const.js.  `inject-all` calls `environment`, `inject-all` calls `build-vars` which also calls `environment`

I'll look more into this issue this weekend

**Comment by gruppjo** [comment] 2016-05-07 12:59
We migrated `gulp-inject` from 3.0.0 to 4.0.0 in the last update. I'm starting to suspect this to be the cause of the problem. Can anyone experiencing this issue and downgrade to 3.0.0 in their `package.json` (https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/package.json#L23) and then run ` npm install` to confirm that the problem still occurs?

**Comment by ruddell** [comment] 2016-05-07 18:01
When I downgraded to 3.0.0, the issue disappears.

I still have the css get deleted like you mention.  I generated foobar.ctrl.js and foobar2.ctrl.js, line 72 of the gulp log shows the css being deleted from the .tmp folder http://pastebin.com/mKrhRfsy

**Comment by gruppjo** [comment] 2016-05-09 08:23
Thanks for verifying!
The CSS issue I don't mind so much, since it doesn't occur that often and doesn't break/delete anything. The gulp tasks need some general overhaul anyway but I'm waiting for gulp 4 to come around, since we'll have to rewrite them then anyhow.

**Comment by gruppjo** [comment] 2016-06-02 09:49
@ruddell, did you have a chance to test this with gulp-inject@4.1.0?

**Comment by ruddell** [comment] 2016-06-03 01:04
I can no longer reproduce the error using gulp-inject@4.1.0.

SCSS still fails to compile occasionally

**Comment by gruppjo** [comment] 2016-06-03 07:25
Nice. Thanks for your valuable input @ruddell! Then no more actions are necessary. Let's hope this issue doesn't return.
The css issue might be related to this issue and might be fixed by this watch task modification https://github.com/mwaylabs/generator-m-ionic/issues/317#issuecomment-222931884. If you have the time let me know if this helps.

**Closed by gruppjo** 2016-06-03 07:25 UTC
Labels: bug, generator - gulp
