### ISSUE TITLE
Develop update strategy for gulp tasks

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#176] opened 2015-04-24 14:25 UTC
We recently came up with the idea that sometimes, especially with bigger projects, we want to update the generator version the project was setup with.

For the sub generators this is no problem since they are called with yo m:subgenerator

But for all other tasks called by gulp, they are stuck at the generator-m version the project was setup with.
Maybe its possible to move the gulp tasks to a node module? This way you could update them trough npm.

**Comment by DrMabuse23** [comment] 2015-04-27 11:56
I think sounds like sub-module in git

**Comment by gruppjo** [comment] 2015-04-29 11:49
I like the idea of a npm module. I'm not sure however if that will work when the gulp tasks need to be templated for the generator, which is not the case yet(?).

**Comment by gruppjo** [comment] 2016-03-22 06:56
this is related to #158

**Comment by gruppjo** [comment] 2017-01-27 16:17
@MathiasTim, still relevant?

**Comment by gruppjo** [comment] 2017-02-01 14:33
closing, since the issue is outdated. Please feel free to comment, when you feel otherwise.

**Closed by gruppjo** 2017-02-01 14:33 UTC
Labels: generator - gulp, maintenance
