### ISSUE TITLE
Watcher compiles in endless ..

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m-ionic#443] opened 2016-10-24 15:26 UTC
Hi always when i change a attribute in the scss files the compiler ends in endless loop. 

``` shell
node -v
v6.6.0

npm -v
3.10.7

> os.platform()
'darwin'
```

i use

``` shell
$ gulp watch 
```

and then change the attr name then i get

``` shell
[17:20:05] Finished 'styles' after 318 ms
[17:20:10] Starting 'clean'...
[17:20:10] Finished 'clean' after 4.66 ms
[17:20:10] Starting 'styles'...
Error in plugin 'sass'
Message:
    app/main/styles/_components.scss
Error: Undefined variable: "$dtts-orange".
        on line 42 of app/main/styles/_components.scss
>>       color: $dtts-orange;
   -------------^

[17:20:10] Finished 'styles' after 271 ms
[17:20:12] Starting 'clean'...
[17:20:12] Finished 'clean' after 4.53 ms
[17:20:12] Starting 'styles'...
[17:20:15] Finished 'styles' after 2.77 s
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was added, running tasks...
[17:20:15] Starting 'clean'...
[17:20:15] Starting 'wiredep'...
[17:20:15] Starting 'bower-fonts'...
[17:20:16] Starting 'environment'...
[17:20:16] gulp-inject Nothing to inject into main/constants/config-const.js.
[17:20:16] Finished 'wiredep' after 408 ms
[17:20:16] Finished 'clean' after 413 ms
[17:20:16] Starting 'styles'...
[17:20:16] Finished 'environment' after 371 ms
[17:20:16] Starting 'build-vars'...
[17:20:16] Starting 'environment'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:16] Starting 'eslint'...
[17:20:16] Starting 'jsonlint'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was deleted, running tasks...
[17:20:18] Starting 'clean'...
[17:20:18] Starting 'wiredep'...
[17:20:18] gulp-inject Nothing to inject into main/constants/config-const.js.
[17:20:19] gulp-inject Nothing to inject into main/constants/config-const.js.
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:19] Finished 'styles' after 3.31 s
[17:20:19] Finished 'build-vars' after 3.39 s
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was added, running tasks...
[17:20:20] Finished 'environment' after 3.81 s
[17:20:20] Starting 'build-vars'...
[17:20:20] Starting 'environment'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:20] Finished 'wiredep' after 1.79 s
[17:20:20] Finished 'clean' after 1.8 s
[17:20:20] Starting 'styles'...
[17:20:20] gulp-inject Nothing to inject into main/constants/config-const.js.
[17:20:20] gulp-inject Nothing to inject into main/constants/config-const.js.
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was deleted, running tasks...
[17:20:20] Starting 'clean'...
[17:20:20] Starting 'wiredep'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:23] Finished 'build-vars' after 2.92 s
[17:20:23] Finished 'environment' after 2.91 s
[17:20:23] Finished 'styles' after 2.98 s
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
[17:20:23] Finished 'wiredep' after 2.9 s
[17:20:23] Finished 'clean' after 2.91 s
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was added, running tasks...
[17:20:23] Starting 'clean'...
[17:20:23] Starting 'wiredep'...
[17:20:23] Starting 'environment'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was deleted, running tasks...
[17:20:23] Finished 'bower-fonts' after 7.7 s
[17:20:23] Finished 'jsonlint' after 7.19 s
[17:20:23] Finished 'clean' after 176 ms
[17:20:23] Starting 'styles'...
[17:20:23] gulp-inject Nothing to inject into main/constants/config-const.js.
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:24] Starting 'jsonlint'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
[17:20:26] Finished 'wiredep' after 2.69 s
[17:20:26] Finished 'environment' after 2.69 s
[17:20:26] Starting 'build-vars'...
[17:20:26] Starting 'environment'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:26] Finished 'styles' after 2.97 s
[17:20:26] gulp-inject Nothing to inject into main/constants/config-const.js.
[17:20:26] gulp-inject Nothing to inject into main/constants/config-const.js.
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:27] Finished 'build-vars' after 838 ms
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was added, running tasks...
[17:20:27] Starting 'clean'...
[17:20:27] Starting 'wiredep'...
[17:20:27] Starting 'bower-fonts'...
[17:20:27] Finished 'environment' after 911 ms
[17:20:27] Starting 'build-vars'...
[17:20:27] gulp-inject Nothing to inject into main/constants/config-const.js.
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
[17:20:27] Finished 'wiredep' after 507 ms
[17:20:27] Finished 'clean' after 510 ms
[17:20:27] Starting 'styles'...
[17:20:27] Finished 'build-vars' after 472 ms
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was deleted, running tasks...
[17:20:28] Starting 'clean'...
[17:20:28] Starting 'wiredep'...
[17:20:28] Starting 'environment'...
[17:20:28] Finished 'jsonlint' after 4.17 s
[17:20:30] Finished 'clean' after 2.27 s
[17:20:30] gulp-inject Nothing to inject into main/constants/config-const.js.
[17:20:30] Finished 'styles' after 2.67 s
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
[17:20:30] Starting 'jsonlint'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
[17:20:30] Finished 'wiredep' after 2.66 s
[17:20:30] Finished 'environment' after 2.67 s
[17:20:30] Starting 'build-vars'...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/.tmp/main/styles/main.css was added, running tasks...
[17:20:30] Starting 'clean'...
[17:20:30] Starting 'wiredep'...
[17:20:30] Starting 'environment'...
[17:20:31] gulp-inject Nothing to inject into main/constants/config-const.js.
[17:20:31] gulp-inject Nothing to inject into main/constants/config-const.js.
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/main/constants/config-const.js was changed, running tasks...
[BS] Reloading Browsers...
File /Users/pascalbrewing/htdocs/whitelabel-relution-ionic/client/app/index.html was changed, running tasks...
[BS] Reloading Browsers...
[17:20:31] Finished 'build-vars' after 730 ms
[17:20:31] Finished 'wiredep' after 532 ms
[17:20:31] Finished 'clean' after 544 ms
[17:20:31] Starting 'styles'...
[17:20:31] Finished 'environment' after 547 ms
[17:20:31] Finished 'bower-fonts' after 4.2 s
^C
Pascals-MacBook-Pro:client pascalbrewing$ gulp watch --env=dev-mway
```

i have to cancel it and start again. Sometimes the main.css from the temp folder is missing or sometimes the config.const is empty, whatever it spends a lot of time to check terminal => stop => start again.

**Comment by gruppjo** [comment] 2017-02-01 14:32
closing, since the issue is outdated. Please feel free to comment, when you feel otherwise.

**Closed by gruppjo** 2017-02-01 14:32 UTC
